FROM zhangsheng377/check_rss_base:latest
# ENTRYPOINT []

RUN git clone https://github.com/zhangsheng377/check_rss.git --depth=1
ARG FQTT_SEND_KEY
RUN echo "ftqq_sendkey = \"$FQTT_SEND_KEY\" "\
> /check_rss/UTILS/config_ftqq.py

RUN git clone https://github.com/BZ-coding/database_factory --depth=1 /check_rss/UTILS/database_factory
RUN git clone https://github.com/BZ-coding/cache_redis --depth=1 /check_rss/UTILS/cache_redis

WORKDIR /check_rss

# CMD ["/bin/bash"]
