FROM zhangsheng377/check_rss_base:latest
# ENTRYPOINT []

RUN git clone --recursive https://github.com/zhangsheng377/check_rss.git --depth=1
ARG FQTT_SEND_KEY
ARG BZ_SEND_KEY
RUN echo "ftqq_sendkey = \"$FQTT_SEND_KEY\" \nbz_sendkey = \"$BZ_SEND_KEY\" "\
> /check_rss/UTILS/config_ftqq.py

WORKDIR /check_rss

# CMD ["/bin/bash"]
