name: check_rss
channels:
    - conda-forge
    - defaults
dependencies:
  - feedparser
  - pymongo
  - requests
  - flask
  - gevent
  - redis
  - pip
  - pip:
    - you-get
# prefix: /mnt/nfs/zsd_server/miniconda3/envs/check_rss
